[versions]
agp = "8.12.3"
androidx-lifecycle = "2.9.6"
kotlin = "2.2.21"
koin = "4.1.1"
ktor = "3.3.2"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.11.0" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version = "1.10.2" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.9.0" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.7.1" }
material-kolor = { module = "com.materialkolor:material-kolor", version = "4.0.4" }
koalaplot-core = { module = "io.github.koalaplot:koalaplot-core", version = "0.9.1" }

pepper-bdd-reports-api = { module = "io.github.vooft:pepper-bdd-reports-api", version = "0.4.1" }
compose-treeview-core = { module = "io.github.vooft:compose-treeview-core", version = "0.3.0" }

lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version = "2.9.6" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version = "2.9.1" }

koin-compose-viewmodel-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation", version.ref = "koin" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose-multiplatform = { id = "org.jetbrains.compose", version = "1.9.3" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jmailen.kotlinter", version = "5.2.0" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.8" }
